###
POST https://teste-api-typescript.herokuapp.com/books
Content-Type: application/json

{
    "title": "livro teste",
    "author": "gui"
}

###
GET https://teste-api-typescript.herokuapp.com/books
Content-Type: application/json

###
GET https://teste-api-typescript.herokuapp.com/books/622a22d0be566fcd3a86dfa9
Content-Type: application/json

###
GET http://localhost:5000/books/
Content-Type: application/json

###
POST http://localhost:5000/books
Content-Type: application/json

{
    "nome": "livro teste 2",
    "descricao": "teste 2",
    "preco": 0,
    "marca": "teste 2",
    "isbn": "teste 2"
}

###
PUT http://localhost:5000/books/62277e3879fb76ff3e581ec8
Content-Type: application/json

{
    "title": "livro de Typescript",
    "author": "Gui"
}

###
DELETE  http://localhost:5000/books/622f75129fc9247edd4fa8f1
Content-Type: application/json


###
PATCH http://localhost:5000/books/62277e3879fb76ff3e581ec8
Content-Type: application/json

  {   
    "title": "livro de Typescript 3"  
  }