###
POST http://localhost:5000/books
Content-Type: application/json

{
    "title": "livro teste",
    "author": "gui"
}

###
GET http://localhost:5000/books
Content-Type: application/json

###
GET http://localhost:5000/books/62277e3879fb76ff3e581ec8
Content-Type: application/json

###
PUT http://localhost:5000/books/62277e3879fb76ff3e581ec8
Content-Type: application/json

{
    "title": "livro de Typescript",
    "author": "Gui"
}

###
DELETE  http://localhost:5000/books/62277e3879fb76ff3e581ec8
Content-Type: application/json
